image: docker:latest
services:
    - docker:dind
    
stages:
  - build
  - deploy

before_script:
  - sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories
  - apk upgrade --update-cache --available
  - apk --no-cache add git gzip gcc musl-dev tree
  - apk --no-cache add go
  - mkdir -p /goSrc/src/github.com/Toyz
  - cp -r /builds/Toyz/RandomWP /goSrc/src/github.com/Toyz/RandomWP
  - export GOPATH=/goSrc
  - go get github.com/tools/godep
  - go get -u github.com/shuLhan/go-bindata/...
  - export PATH=$PATH:/goSrc/bin
  - cd /goSrc/src/github.com/Toyz/RandomWP
  - mkdir output

build:
  stage: build
  script:
    - godep restore -v
    - go-bindata ./assets/...
    # - CGO_ENABLED=0 GOOS=linux godep go build -o pw -a -installsuffix cgo -ldflags '-w -s'
    - CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -ldflags '-H windowsgui' -o ./output/RandomWP_x86.exe
    - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags '-H windowsgui'  -o ./output/RandomWP_x64.exe
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:staging" .
    - docker push "$CI_REGISTRY_IMAGE:staging"
  artifacts:
    paths:
      - ./output/RandomWP_x86.exe
      - ./output/RandomWP_x64.exe