image: "portown/alpine-mingw-w64:latest"
services:
    - docker:dind
    
stages:
  - build
  - deploy

before_script:
  - apk upgrade --update-cache --available
  - apk --no-cache add git gzip gcc musl-dev tree gtk+3.0
  - apk --no-cache add go
  - mkdir -p /goSrc/src/github.com/Toyz
  - cp -r /builds/Toyz/RandomWP /goSrc/src/github.com/Toyz/RandomWP
  - export GOPATH=/goSrc
  - go get github.com/tools/godep
  - go get -u github.com/shuLhan/go-bindata/...
  - export PATH=$PATH:/goSrc/bin
  - cd /goSrc/src/github.com/Toyz/RandomWP
  - mkdir $CI_PROJECT_DIR/output

build:
  stage: build
  script:
    - godep restore -v
    - go-bindata ./assets/...
    # - CGO_ENABLED=0 GOOS=linux godep go build -o pw -a -installsuffix cgo -ldflags '-w -s'
    - CGO_ENABLED=0 GOOS=windows GOARCH=386 CC="x86_64-w64-mingw32-gcc -fvisibility=hidden -static-libgcc -fno-stack-protector -D_FORTIFY_SOURCE=0 -lssp" go build -ldflags '-H windowsgui' -o $CI_PROJECT_DIR/output/RandomWP_x86.exe
    - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 CC="x86_64-w64-mingw32-gcc -fvisibility=hidden -static-libgcc -fno-stack-protector -D_FORTIFY_SOURCE=0 -lssp" go build -ldflags '-H windowsgui' -o $CI_PROJECT_DIR/output/RandomWP_x64.exe
  artifacts:
    paths:
      - output