image: docker:latest
services:
    - docker:dind
    
stages:
  - build
  - deploy

before_script:
  - sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories
  - apk upgrade --update-cache --available
  - apk --no-cache add git gzip gcc musl-dev tree git
  - apk --no-cache add go
  - mkdir -p /goSrc/src/github.com/Toyz
  - cp -r /builds/Toyz/RandomWP /goSrc/src/github.com/Toyz/RandomWP
  - export GOPATH=/goSrc
  - go get github.com/tools/godep
  - go get -u github.com/shuLhan/go-bindata/...
  - export PATH=$PATH:/goSrc/bin
  - cd /goSrc/src/github.com/Toyz/RandomWP
  - git rev-parse HEAD > ./assets/version.txt
  - mkdir $CI_PROJECT_DIR/output

stages:
  - build

build:
  stage: build
  script:
    - godep restore -v
    - go-bindata ./assets/...
    # - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o $CI_PROJECT_DIR/RandomWP_x64 -a -installsuffix cgo -ldflags '-w -s'
    - CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -ldflags '-H windowsgui' -o $CI_PROJECT_DIR/RandomWP_x86.exe
    - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags '-H windowsgui'  -o $CI_PROJECT_DIR/RandomWP_x64.exe
  artifacts:
    paths:
      - RandomWP_x86.exe
      - RandomWP_x64.exe
  only:
    - master
  
build-nightly:
  stage: build
  script:
    - godep restore -v
    - go-bindata ./assets/...
    # - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o $CI_PROJECT_DIR/RandomWP_x64_nightly -a -installsuffix cgo -ldflags '-w -s'
    - CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -ldflags '-H windowsgui' -o $CI_PROJECT_DIR/RandomWP_x86_nightly.exe
    - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags '-H windowsgui'  -o $CI_PROJECT_DIR/RandomWP_x64_nightly.exe
  artifacts:
    paths:
      - RandomWP_x86_nightly.exe
      - RandomWP_x64_nightly.exe
  only:
    - develop